# Generated by Django 2.1.5 on 2019-02-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='descricao',
        ),
        migrations.AddField(
            model_name='departamento',
            name='nome',
            field=models.CharField(default='desenvolvimento', max_length=70),
            preserve_default=False,
        ),
    ]
